###
POST http://localhost:5000/users/register
Content-Type: application/json

{
  "UserName": "Mammer",
  "Password": "Mammer"
}

###

GET http://localhost:5000/users/login
Content-Type: application/json

{
  "userName": "Mammer",
  "password": "Mammer"
}

###
GET http://localhost:5000/users/GetQuiz/bieYO-000