###
POST http://localhost:5000/users/register
Content-Type: application/json

{
  "UserName": "Mammer",
  "Password": "Mammer"
}

###

GET http://localhost:5000/users/login
Content-Type: application/json

{
  "userName": "Mammer",
  "password": "Mammer"
}

###
GET http://localhost:5000/users/GetQuiz/GAqpTo-000

###
GET http://localhost:5000/users/GetQuizWithID/10


### 
DELETE http://localhost:5000/users/DeleteQuiz/6

###
POST http://localhost:5000/users/GetTime
Content-Type: application/json

{
    "currentTime": "2025-03-13T12:00:00",
    "fillerID": 3,
    "quizID": 1
}
###
GET http://localhost:5000/users/CheckToken

###
GET http://localhost:5000/users/CheckUsername/LOCIKA
